### ISSUE TITLE
I can't get access to Google

### ISSUE THREAD

**Issue by lorenzocarreri** [smol-ai/GodMode#175] opened 2023-08-22 06:49 UTC
Hey there, I've tried to access to Google from the ChatGPT window, but it's not working, it says that the browser or app is not secure. See screenshot. 

How do I fix it?

![Screenshot 2023-08-22 at 07 47 29](https://github.com/smol-ai/GodMode/assets/116936398/ab274867-e888-4db1-88f3-d2729b074af0)

**Comment by lorenzocarreri** [comment] 2023-08-22 07:11
Ok, I had to log into Bard first, then ChatGPT. Now it works.

**Comment by lorenzocarreri** [comment] 2023-08-22 16:44
I didn't re-download it, I just signed into Bard.

**Comment by swyxio** [comment] 2023-08-22 16:51
hiya! I've used this a lot personally and never run into that Google error. but its true, basically once you've signed in successfully to Google in any of the tabs, you'll be easily able to sign in to all of them since they just reuse the same auth.

**Comment by AFK-Python** [comment] 2023-08-22 17:35
Works on Anthropic's google login... Maybe have all google auths pop out?

**Comment by swyxio** [comment] 2023-08-22 17:40
> Maybe have all google auths pop out?

thats not something i control unfortunately

**Comment by AFK-Python** [comment] 2023-08-22 17:57
So that behavior is default from Claude and not an option from Bard? Strange...

**Comment by swyxio** [comment] 2023-08-23 01:09
yeah i think google SSO has a few types and Bard happened to pick the one unfriendly one... i will experiment but its hard bc i cant repro it myself

**Comment by jacob-8** [comment] 2023-08-23 12:07
Yes, I can confirm. To workaround the insecure browser on Windows, use the Anthropic login because its Google login is a popup. Then the others that use Google login will be working.

**Comment by vaibhavkumar-sf** [comment] 2023-08-26 15:15
In MAC M1 , latest arm release, no login is working 
![image](https://github.com/smol-ai/GodMode/assets/30282624/f9b56407-0b0f-488e-9a97-a4105e6c93c3)
![image](https://github.com/smol-ai/GodMode/assets/30282624/04bdec4a-8624-4956-b352-65e14cef6e23)

**Comment by swyxio** [comment] 2023-08-29 16:45
consolidating this as duplicate of #11

**Closed by swyxio** 2023-08-29 16:45 UTC
