### ISSUE TITLE
since installing god mode chat gpt no longer works on godmode or on my browser

### ISSUE THREAD

**Issue by lordboun** [smol-ai/GodMode#238] opened 2023-09-09 13:23 UTC
since installing god mode chat gpt no longer works on godmode or on my browser no more searches are possible
I really don't know what to do anymore and I really need it for my work

![Capture](https://github.com/smol-ai/GodMode/assets/130802860/a6088601-2af8-4b6c-b16c-262ee577e86e)
![eee](https://github.com/smol-ai/GodMode/assets/130802860/3abd5c2c-4473-4183-9d60-f7e7e162bb6a)

**Comment by lgandecki** [comment] 2023-09-10 10:15
if you really need it for your work, why don't you create a new account? or use https://www.typingmind.com/ with openai or https://openrouter.ai/ api key? :) it might be a coincidence that chatgpt stopped working, but one way or another there are other ways accessing it

**Comment by lordboun** [comment] 2023-09-10 17:11
As for the account I don't have another phone number but I'm going to try to see if it works with another account and for the rest I admit I don't know enough about it to know how to use both tools that you sent me

**Comment by seanoliver** [comment] 2023-09-12 15:46
@lordboun have you been able to access your ChatGPT account yet? I agree with @lgandecki that it might just be an unfortunate coincidence.

I'm going to close this issue since I don't think there's anything product-related we can do to resolve, but feel free to re-open if you have more information indicating GodMode is somehow connected to the account issue.

**Closed by seanoliver** 2023-09-12 15:46 UTC

**Comment by lordboun** [comment] 2023-09-13 15:02
I tried to change accounts etc and this came from my installation of godmod

**Comment by lordboun** [comment] 2023-09-13 15:03
can you help me please I really need gpt chat on my pc

**Comment by lgandecki** [comment] 2023-09-13 15:17
If you don't know how to use typingmind, use perplexity.ai instead, you can select "writing" mode that will not search through the web. It's basically the same as gpt-4. I don't think anyone will be able to help you more here, as the issue is not related to this package at this point. I'm sorry.
This is a free and open source project and you use it without any guarantee, having said that, many people use this software and no-one got blocked as far as we know, so it seems really unlikely GodMode was the cause here. You can also contact the help.openai.com as the error message suggests. To be honest using GodMode shouldn't even cause any problems in terms of not complying with their conditions.
